services:
  postgres:
    image: ankane/pgvector:latest # This image includes the vector extension
    container_name: rag_db
    environment:
      POSTGRES_USER: rag_user
      POSTGRES_PASSWORD: rag
      POSTGRES_DB: rag_db
    ports:
      - "6012:5432"
    volumes:
      - rag_data:/var/lib/postgresql/data

  redis:
    image: redis:6.0
    container_name: rag_redis
    ports:
      - "6013:6379"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: rag_frontend
    ports:
      - "5115:80"

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: rag_backend
    ports:
      - "5116:8000"
    depends_on:
      - postgres
      - redis
      - context-server
      # - model
    env_file:
      - ./server/.env

  context-server:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: rag_context_server
    ports:
      - "5117:8000"
    env_file:
      - ./database/.env

  # model:
  #   build:
  #     context: ./model
  #     dockerfile: Dockerfile
  #   container_name: rag_model
  #   env_file:
  #     - ./model/.env

volumes:
  rag_data:
